config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  get 'menu' , to: 'menu#list'

  get 'signup' , to: 'signup#new'
  post 'signup', to: 'signup#create'

  get 'login', to:'login#new'
  post 'login', to:'login#create'

  delete 'logout', to: 'login#destroy'

  get 'order_item', to: 'order_item#list'
  post 'order_item', to: 'order_item#create'
  put 'order_item', to: 'order_item#decrement'

  post 'cart', to: 'cart#create'
  put 'cart', to: 'cart#decrement'

  get 'search', to: 'search#index'

  post 'menu', to: 'order_item#create'
  put 'menu', to: 'order_item#decrement'

  # get 'payment', to: 'payment#index'
  post 'payment', to: 'payment#index'
  #  resources :order_item, only: [:create]



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current<ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :menus, through: :order_items

  # def clear
  #   order_items.destroy_all
  # end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email,presence: true
  has_many :orders, dependent: :destroy


end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :find_order
  def create
    @order_item=@order.order_items.find_by(menu_id: order_item_params[:menu_id])
    if @order_item
      if @order_item.update(quantity: @order_item.quantity+1)
        redirect_to order_item_path,notice: "Item Quantity updated"
      else
        redirect_to  order_item_path, alert: "Item Quantity could not be updated"
      end
    else
      @order_item=@order.order_items.build(order_item_params.merge(quantity: 1))
      if @order_item.save
        redirect_to  order_item_path, notice: "Item is added to the cart"
      else
        redirect_to  order_item_path, alert: "Item could not be added"
      end
    end

  end
  def decrement
    @order_item=@order.order_items.find_by(menu_id: order_item_params[:menu_id])
   if @order_item.quantity>1
     if @order_item.update(quantity: @order_item.quantity-1)
       redirect_to  order_item_path, notice: "quantity is reduced"
     else
      redirect_to  order_item_path, alert: "quantity could not be updated"

     end
    else
      @order_item.destroy
      redirect_to  order_item_path, alert: "Item deleted"
   end
  end
def show
    @sum_order=sum_of_item(current_user.id)

end
private

def find_order
  @order = current_user.orders.last
  if @order.nil?
    current_user.order.create
  end
end


  def order_item_params
    params.require(:order_item).permit(:menu_id)
  end



end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
    @show_navbar=true
  end

  def create
      user=User.find_by(email: params[:email])
      if user.present? && user.authenticate(params[:password])
          session[:user_id]=user.id
          Order.create(user_id: user.id)
          redirect_to menu_path,notice: 'logged in succesfully'
      else
          flash[:alert]='invalid email or password'
          render :new
      end
  end
  def destroy
    current_user.orders.destroy_all
    session[:user_id]=nil
    reset_session
    redirect_to root_path,notice: 'logged out'
end
private
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @show_navbar=true
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def list
    @show_navbar=false
    @show_nav=true
    @menu=Menu.all

  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:user_id)
  end
end

app/controllers/order_item_controller.rb
class OrderItemController < ApplicationController
  before_action :find_order


  def create
    @order_item=@order.order_items.find_by(menu_id: order_item_params[:menu_id])
    if @order_item
      if @order_item.update(quantity: @order_item.quantity+1)
        redirect_to menu_path,notice: "Item Quantity updated"
      else
        redirect_to menu_path, alert: "Item Quantity could not be updated"
      end
    else
      @order_item=@order.order_items.build(order_item_params.merge(quantity: 1))
      if @order_item.save
        redirect_to menu_path, notice: "Item is added to the cart"
      else
        redirect_to menu_path, alert: "Item could not be added"
      end
    end

  end
  def decrement
    @order_item=@order.order_items.find_by(menu_id: order_item_params[:menu_id])
   if @order_item.quantity>1
     if @order_item.update(quantity: @order_item.quantity-1)
       redirect_to menu_path, notice: "quantity is reduced"
     else
      redirect_to menu_path, alert: "quantity could not be updated"

     end
    else
      @order_item.destroy
      redirect_to menu_path, alert: "Item deleted"
   end
  end
  def list
    @order_list=current_user.orders.last.order_items
    @show_nar=true
    @sum_order=calculate_sum(current_user.id)
    p @sum_order
    puts
    puts
    puts

  end

  # def destroy
  #   @order_item.destroy
  #   redirect_to menu_path, alert: "Item destroyed"
  # end

  private
  def calculate_sum(user_id)
    current_order = Order.find_by(user_id: user_id)
    if current_order
      cost = current_order.order_items.map { |item| menu_price(item.menu_id) * item.quantity }
       return cost.reduce(0, :+)

  end
end
  def find_order
    @order = current_user.orders.last
    if @order.nil?
      current_user.order.create
    end
  end

  def order_item_params
    params.require(:order_item).permit(:menu_id)
  end

  def menu_price(menu_id)
    menu_item = Menu.find_by(id: menu_id)
    menu_item ? menu_item.cost: 0
  end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @show_nav=true
    @menu=Menu.all
    if params[:query].present?
      @menu=@menu.where("name LIKE ?", "%#{params[:query]}%")
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def new
    @show_navbar=true
    @user=User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      create_order_for_user(@user.id)
      redirect_to menu_path, notice: "Successfully created an account"
    else
      render :new
    end
  end
  def user_params
    params.require(:user).permit(:name, :email, :phno, :password)
  end

  private
def create_order_for_user(user_id)
  Order.create(user_id: user_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/order_item/list.html.erb
<style>
.form-style
{
  display:inline;
}
 body {
      background-image: url('background.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
    }
    h1{
      text-align: center;
    }
   
    .cont {
  position:relative;
  width: 100%;
}

.cont img {
  width: 100%;
  height: auto;
  opacity: 0.5
}

.text {
  position: absolute; 
  top: 50%; 
  left: 50%; 
  transform: translate(-50%, -50%);
  
  
  min-height: 100%;
}
table {
  height: 100%;
  width:100%;
  table-layout:fixed;
  background-color: rgba(255, 255, 255, 0.8);
  opacity:0.7;
}
table td {
  width: auto;
}
</style>
<body>
<div class="cont">
<%= image_tag 'background.jpg', alt: 'My Logo', style:"width:100%; height: 80%;"%>

<div class="text">
<h1 class="heading">Cart List</h1>


     
<table class="table table-striped" >
  <thead>
    <tr>
     
      <th>Name</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @order_list.each do |item|%>
      <tr>
        <td><%= item.menu.name%></td>
        <td><%= item.menu.cost%></td>
        <td><%= item.quantity %></td>

        <td> <%= form_with(model: OrderItem, url: cart_path, method: :post,class:"form-style") do |form|%>
         <%= form.hidden_field :menu_id, value: item.menu.id %>
        <%= form.submit "+" %>
        <% end %>
        <%= form_with( model: OrderItem,url: cart_path, method: :put,class:"form-style") do |form|%>
        <%= form.hidden_field :menu_id, value: item.menu.id %>
         <%= form.submit "-",class: "decrement" %>
         <%end%>
        </td>
    </tr>
    <%end%>
  </tbody>
</table>
 <% if !@sum_order.nil? %>
  <p style="text-align:center;">Total: <%= @sum_order %></p>
<% else %>
  <p style="text-align:center;">Your cart is empty.</p>
<% end %>
<div>
  <%= button_to "Checkout", payment_path,style:"background-color:#00b359; width: 750px; height: 40px; font-size:25px;display:flex; justify-content:center;align-items:center;",method: :post%>
  </div>
</div>
</div>
</body>