config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  get 'menu' , to: 'menu#list'

  get 'signup' , to: 'signup#new'
  post 'signup', to: 'signup#create'

  get 'login', to:'login#new'
  post 'login', to:'login#create'

  delete 'logout', to: 'login#destroy'

  get 'order_item', to: 'order_item#list'
  post 'order_item', to: 'order_item#create'
  put 'order_item', to: 'order_item#decrement'

  post 'cart', to: 'cart#create'
  put 'cart', to: 'cart#decrement'

  get 'search', to: 'search#index'

  post 'menu', to: 'order_item#create'
  put 'menu', to: 'order_item#decrement'

  # get 'payment', to: 'payment#index'
  post 'payment', to: 'payment#index'
  #  resources :order_item, only: [:create]



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current<ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :menus, through: :order_items

  # def clear
  #   order_items.destroy_all
  # end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email,presence: true
  has_many :orders, dependent: :destroy


end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :find_order
  def create
    @order_item=@order.order_items.find_by(menu_id: order_item_params[:menu_id])
    if @order_item
      if @order_item.update(quantity: @order_item.quantity+1)
        redirect_to order_item_path,notice: "Item Quantity updated"
      else
        redirect_to  order_item_path, alert: "Item Quantity could not be updated"
      end
    else
      @order_item=@order.order_items.build(order_item_params.merge(quantity: 1))
      if @order_item.save
        redirect_to  order_item_path, notice: "Item is added to the cart"
      else
        redirect_to  order_item_path, alert: "Item could not be added"
      end
    end

  end
  def decrement
    @order_item=@order.order_items.find_by(menu_id: order_item_params[:menu_id])
   if @order_item.quantity>1
     if @order_item.update(quantity: @order_item.quantity-1)
       redirect_to  order_item_path, notice: "quantity is reduced"
     else
      redirect_to  order_item_path, alert: "quantity could not be updated"

     end
    else
      @order_item.destroy
      redirect_to  order_item_path, alert: "Item deleted"
   end
  end
def show
    @sum_order=sum_of_item(current_user.id)

end
private

def find_order
  @order = current_user.orders.last
  if @order.nil?
    current_user.order.create
  end
end


  def order_item_params
    params.require(:order_item).permit(:menu_id)
  end



end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
    @show_navbar=true
  end

  def create
      user=User.find_by(email: params[:email])
      if user.present? && user.authenticate(params[:password])
          session[:user_id]=user.id
          Order.create(user_id: user.id)
          redirect_to menu_path,notice: 'logged in succesfully'
      else
          flash[:alert]='invalid email or password'
          render :new
      end
  end
  def destroy
    current_user.orders.destroy_all
    session[:user_id]=nil
    reset_session
    redirect_to root_path,notice: 'logged out'
end
private
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @show_navbar=true
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def list
    @show_navbar=false
    @show_nav=true
    @menu=Menu.all

  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
  <% if @show_navbar %>
   <%= render partial:"shared/navbar"%> 
   <%end%>
   <% if @show_nav %>
   <%= render partial:"shared/nav"%> 
   <%end%>
   <% if @show_nar %>
   <%= render partial:"shared/nar"%> 
   <%end%>
   <%= render partial:"shared/footer"%> 
   <%= render partial:"shared/flash"%> 
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<script>
document.addEventListener("DOMContentLoaded", function() {
    setTimeout(function() {
      $("#notice, #alert").fadeOut("slow");
    }, 3000); // Fade out messages after 3 seconds (adjust as needed)
  });
</script>

<% if flash[:notice] %>
<div id="notice"class="alert alert-info mt-4"><%= flash[:notice] %></div>
<%end%>
<% if flash[:alert] %>
<div id="alert"class="alert alert-warning mt-4"><%=flash[:alert] %></div>
<%end%>

app/views/shared/_footer.html.erb
<style>
.main-footer {
 position: fixed;
  bottom: 0;
  width: 100%;
  background-color: #666666;
  color: black;
  text-align: center;
  padding: 5px;
}
</style>
<footer class="main-footer">
    <p>copyright &copy; 2024, Resto</p>
</footer>

app/views/shared/_nar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%=link_to "Resto",root_path,class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%=link_to "Home",root_path,class:"nav-link" %>
          
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
             
        <li class="nav-item">
        <%=button_to "logout", logout_path,class:"nav-link",method: :delete%>
        </li>
       
        </ul>

    </div>
  </div>
</nav>

app/views/shared/_nav.html.erb
<style>
.navbar {
 position: fixed;
  width: 100%;
  background-color: #666666;
  color: black;
  text-align: center;
  
}
</style>
<nav class="navbar navbar-expand-lg ">
  <div class="container-fluid">
  <%=link_to "Resto",root_path,class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%=link_to "Home",root_path,class:"nav-link"%>
          
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%=link_to order_item_path,class:"nav-link" do%>
        <i class="	fa fa-cart-plus" style="font-size:24px"></i>
        <%end%>
        </li>         
        <li class="nav-item">
        <%=button_to "logout", logout_path,class:"nav-link",method: :delete%>
        </li>
       
        </ul>

    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<style>
.navbar {
 position: fixed;
 
  width: 100%;
  background-color: #666666;
  color: black;
  text-align: center;
  padding: 5px;
}
</style>
<nav class="navbar navbar-expand-lg ">
  <div class="container-fluid">
  <%=link_to "Resto",root_path,class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%=link_to "Home",root_path,class:"nav-link" %>
          
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        
        
        <% unless params[:controller] == "signup" && params[:action] == "new" %>
        <li class="nav-item">
        
        <%=link_to "sign-up",signup_path,class:"nav-link"%>
        </li>
        <%end%>
        <% unless params[:controller] == "login" && params[:action] == "new" %>
        <li class="nav-item">
        <%=link_to "login",login_path,class:"nav-link"%>
        </li>
        <%end%>
       <% unless params[:controller] == "main" && params[:action] == "index" %>
        <li class="nav-item">
        <%=button_to "logout",root_path,class:"nav-link"%>
        </li>
        <%end%>
       
        </ul>

    </div>
  </div>
</nav>